// The content is drawn from Lucas's supplied site snapshot. Links remain the originals.
const notion = 'https://lucasdino.notion.site/';
export const stories = [
  {id:'nebraska',n:'01',label:'NEBRASKA',title:'First, there was corn.',tag:'THE STARTING POINT',summary:'Nebraska → everywhere',color:'#eada65',x:126,y:231,r:40,
   copy:'I’m from Nebraska. The round-the-world trip started in McCook, at a literal one-room airport. You can take a boy out of Nebraska…',
   body:'I grew up in Nebraska, studied finance, and worked as an investment banker for two years. When I left for my gap year, I carried one backpack and had no return date. First stop: a family reunion. Then a flight out of McCook’s one-room airport.',
   image:'/assets/pics/sabbatical/nebraskacows.jpg',alt:'Cows in a green Nebraska pasture',link:'#postcards-title',linkLabel:'Take the long way round',links:[['Why I changed direction',notion+'Why-Pivot-7736665e93394c3886f78950ca66f7d2?pvs=4']]},
  {id:'banking',n:'02',label:'BANKING',title:'A spreadsheet phase.',tag:'TWO YEARS IN FINANCE',summary:'Investment banking',color:'#f0eddf',x:345,y:242,r:41,
   copy:'I studied finance and spent two years in investment banking. I even tracked my working hours. Eventually, I wanted to spend that energy on something else.',
   body:'Before machine learning, I worked as an investment banking analyst at FT Partners. I tracked my hours across the two years and wrote about them. I also wrote about the decision to leave, take a gap year, and make a serious attempt at a different field.',
   link:notion+'Why-Pivot-7736665e93394c3886f78950ca66f7d2?pvs=4',linkLabel:'Read “Why Pivot?”',links:[['Why Pivot?',notion+'Why-Pivot-7736665e93394c3886f78950ca66f7d2?pvs=4'],['My actual working hours',notion+'My-Honest-Working-Hours-as-an-Investment-Banking-Analyst-03845324522a4b7785f6b752cf8b0da2?pvs=4']]},
  {id:'detour',n:'03',label:'THE BIG<br>DETOUR',title:'An extremely scenic pivot.',tag:'153 DAYS · 22 FLIGHTS',summary:'Studying, with side quests',color:'#f46535',x:238,y:332,r:52,
   copy:'I left banking to study machine learning. Doing that from Airbnbs and pet sits seemed more interesting than staying home. Greece, Australia, and a lot of linear algebra followed.',
   body:'I wanted to find out whether machine learning was what I really wanted to pursue. So I spent my year off studying, with a five-month trip woven through it. There were long stays, hikes, hostels, pets, family, and plenty of hours on my laptop.',
   image:'/assets/pics/sabbatical/olympus.jpg',alt:'On the rocky slopes of Mount Olympus',link:'#postcards-title',linkLabel:'Open the travel postcards',links:[['What I studied on my year off','https://www.notion.so/lucasdino/What-I-Studied-on-my-Year-Off-271c748e5e4a80c6bc90d2b6e1edf9d6'],['Travel postcards','#postcards-title']]},
  {id:'research',n:'04',label:'RESEARCH',title:'Thinking about thinking.',tag:'UCSD · RL + LANGUAGE MODELS',summary:'Chess, reasoning, and RL',color:'#233fc7',x:116,y:425,r:43,
   copy:'At UCSD, I studied how language-model reasoning changes through fine-tuning and reinforcement learning, using chess. That work became a NeurIPS workshop talk and an ICML paper.',
   body:'With PEARLS Lab at UCSD, I worked on reinforcement learning for language models. Our chess study examined how different fine-tuning datasets affect later RL performance and reasoning. A key wrinkle: a model can choose strong moves while its explanation is inconsistent with those moves. I also worked with UCSD ProgSys on neurosymbolic approaches to ARC-AGI.',
   image:'/assets/thumbnails/llmchess_takeaway.jpg',alt:'Results from Lucas’s chess reasoning research',link:'https://arxiv.org/abs/2604.05134',linkLabel:'Read the chess reasoning paper',note:'ICML 2026 · NeurIPS 2025 FoRLM Workshop (Oral)',links:[['How Reasoning Evolves from Post-Training Data','https://arxiv.org/abs/2604.05134'],['A* Neural Guided Search on ARC-AGI',notion+'Attempted-Neural-A-Guided-Search-on-ARC-AGI-171c748e5e4a801796f6d7e13f78714c?pvs=4'],['PEARLS Lab','https://pearls-lab.github.io/']]},
  {id:'projects',n:'05',label:'SIDE<br>PROJECTS',title:'Let’s see if this works.',tag:'THINGS I’VE BUILT',summary:'Dungeons, drivers, robots',color:'#eada65',x:367,y:411,r:43,
   copy:'A dungeon generator. A reinforcement-learning gym. A self-driving rover. A racing game whose driver had to learn from scratch. I like getting my hands dirty.',
   body:'I built Dungeon Coder to generate assets and interactive 3D dungeons with React, Three.js, and self-hosted vision models. Other rabbit holes include an RL benchmarking gym, a ROS2 rover with an EKF-SLAM implementation from scratch, and teaching a Double Q-learning agent to drive a custom racing game.',
   image:'/assets/thumbnails/dungeoncoder_overview.gif',alt:'Dungeon Coder generates and displays an interactive 3D dungeon',link:notion+'Dungeon-Coder-20dc748e5e4a802cb281ce01fe6272b7?source=copy_link',linkLabel:'Enter Dungeon Coder',links:[['Dungeon Coder',notion+'Dungeon-Coder-20dc748e5e4a802cb281ce01fe6272b7?source=copy_link'],['RL Benchmarking Gym',notion+'RL-Benchmarking-300c748e5e4a80cb9a42e3d8be2f7c58?source=copy_link'],['SLAM-based rover autonomy',notion+'4-Wheel-Rover-Autonomous-Control-31ec748e5e4a8081a7c7ec3951d27317?source=copy_link'],['Teaching AI to drive',notion+'Teaching-AI-to-Drive-my-Custom-Racing-Game-214e45ce19704294bd365308a77c68b4?pvs=4'],['Recreating Word2Vec',notion+'Recreating-Word2Vec-25c1e86e08f14087a49c027a85bd5198']]},
  {id:'now',n:'06',label:'RIGHT<br>NOW',title:'Back in the physical world.',tag:'LOS ANGELES · HADRIAN',summary:'Special Projects @ Hadrian',color:'#1b2a55',x:244,y:470,r:33,
   copy:'These days I’m a jack of all trades on Special Projects at Hadrian. I’m in LA. If you’re nearby, or just want to talk, reach out.',
   body:'I’m now working on Special Projects at Hadrian. The through line from finance to machine learning to this? I like learning how things work, then getting involved. If you’re in LA and/or want to chat, you should reach out.',
   link:'https://www.hadrian.co/',linkLabel:'See what Hadrian is building',links:[['Hadrian','https://www.hadrian.co/'],['Say hello on LinkedIn','https://www.linkedin.com/in/lucasdionisopoulos/'],['Find me on X','https://x.com/dinoacropolis']]}
];
export const postcards = [
 {title:'Kalamata, Greece. With Papou.',file:'papou.jpg',alt:'Lucas’s Papou sitting outside in Kalamata',preview:'A month of machine learning. A visit from family.',text:'I spent about a month in Kalamata studying linear algebra and machine learning. When I was mentally drained, I’d walk to the pier. My Papou and parents visited for a week. He was born in a mountain village nearby, without running water or electricity. I’m forever grateful for his sacrifice to immigrate to the US. I also learned how to Zeibekiko dance.'},
 {title:'Tasmania, Australia. Meet Dot.',file:'dotty.jpg',alt:'Dot the dog during Lucas’s pet sit in Tasmania',preview:'37 days. One excellent study buddy.',text:'Tasmania was perfect for hunkering down and studying. I stayed for 37 days on a pet sit and spent $800 total, including flights and health insurance. Dot was a gem; I absolutely miss this dog. There were great hikes outside Hobart, and I learned to drive on the other side of the road.'},
 {title:'Mount Olympus, Greece. Thanks, Zeus.',file:'olympus.jpg',alt:'The rocky landscape on the climb up Mount Olympus',preview:'A big climb. A very cloudy welcome.',text:'I started the hike at about 3,000 feet. Mytikas, the peak, is about 9,500 feet. It’s a beast of a hike. When I got to the top, clouds rolled in and you couldn’t see anything. Thanks, Zeus. Really appreciate the warm welcome.'},
 {title:'Byron Bay, Australia. Feeding the hostel.',file:'byronbaes.jpg',alt:'Friends together at a hostel in Byron Bay',preview:'The surf was bad. The company was excellent.',text:'I headed to Byron Bay to surf, but the waves were bad and it rained for half the visit. Luckily, the hostel had some great people. On one rainy day I got an urge to cook and made homemade pita and souvlaki for the group. It became one of my favorite hostel moments of the whole trip.'},
 {title:'Delphi, Greece. The long way up.',file:'delphi.jpg',alt:'The ancient ruins of Delphi on a Greek mountainside',preview:'Ruins, a mountainside, and a very good view.',text:'Delphi may be my favorite archaeological site I’ve visited. It is nestled into a valley, and the ancient city crawls up the mountainside. The views plus the ruins: τέλειος. Perfect.'},
 {title:'McCook, Nebraska. Departures.',file:'mccookairport.jpg',alt:'The small airport in McCook, Nebraska',preview:'Around the world starts in a one-room airport.',text:'A literal one-room airport. What better way to kick off a round-the-world trip? One backpack, no return date, and a lot to learn. It would be 153 days and 22 flights before I made it back.'}
];
