"""Build the five static pages. Run from any directory: python build.py."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
NAV = [('index', 'About'), ('professional', 'Work'), ('research', 'Research'), ('personal', 'Elsewhere'), ('contact', 'Contact')]
SOCIAL = [('GitHub', 'https://github.com/lucasdino'), ('LinkedIn', 'https://www.linkedin.com/in/lucasdionisopoulos/'), ('X / Twitter', 'https://x.com/dinoacropolis')]
PIVOT = 'https://lucasdino.notion.site/Why-Pivot-7736665e93394c3886f78950ca66f7d2?pvs=4'
STUDY = 'https://www.notion.so/lucasdino/What-I-Studied-on-my-Year-Off-271c748e5e4a80c6bc90d2b6e1edf9d6'

def arrow():
    return '<span aria-hidden="true" class="link-arrow">↗</span>'

def page(key, title, content, extra_head='', extra_script=''):
    nav = ''.join(f'<a href="{slug}.html" {"aria-current=\"page\"" if slug == key else ""}><span class="nav-no">0{i}</span>{label}</a>' for i, (slug, label) in enumerate(NAV))
    socials = ''.join(f'<a href="{url}">{label} {arrow()}</a>' for label, url in SOCIAL)
    html = f'''<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Lucas Dionisopoulos</title>
<meta name="description" content="Lucas Dionisopoulos. Special Projects at Hadrian, machine learning research, things I've built, and places I've been.">
<meta name="theme-color" content="#2145e5">
<link rel="icon" href="/assets/dino/DinoIcon.ico" type="image/x-icon">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@600;700&family=DM+Sans:wght@400;500;600;700&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet">
{extra_head}<link rel="stylesheet" href="stylesheet.css">
<script defer src="/shared_js/version-switcher.js"></script><script defer src="js/site.js"></script>
</head><body class="page-{key}" id="top">
<a class="skip-link" href="#main">Skip to content</a>
<div class="page-wrap">
<header class="site-header"><a class="monogram" href="index.html" aria-label="Lucas Dionisopoulos home">LD<span class="monogram-dot">.</span></a><nav aria-label="Main navigation">{nav}</nav><div class="version-switcher-mount"></div></header>
<main id="main">{content}</main>
<footer class="site-footer"><div class="footer-top"><a class="footer-name" href="index.html">Lucas<br><em>Dionisopoulos.</em></a><div><p class="eyebrow">Find me here</p><div class="footer-socials">{socials}</div></div><a class="footer-contact" href="contact.html">Say hello <span aria-hidden="true">↗</span></a></div><div class="footer-bottom"><span>From Nebraska. Based in Los Angeles.</span><span>Design with GPT 6 Astra · <a href="#top" data-back-top>Back to top ↑</a></span></div></footer>
</div>{extra_script}</body></html>'''
    (ROOT / f'{key}.html').write_text(html, encoding='utf-8')

home = f'''
<div class="hero-kicker eyebrow"><span>A little about me</span><span>NE → CA <span class="location-dot"></span> Los Angeles</span></div>
<section class="home-hero" aria-labelledby="home-title">
<div class="hero-name"><h1 id="home-title"><span class="first-name">LUCAS</span><span class="last-name">Dionisopoulos<span class="name-period">.</span></span></h1><p class="hero-intro">A Nebraska kid with a few<br>changes of direction.</p></div>
<figure class="portrait"><div class="portrait-image"><img src="/assets/pics/lucasducas.png" width="500" height="500" alt="Lucas Dionisopoulos smiling" fetchpriority="high"></div><figcaption><span>Hi, I'm Lucas.</span><span aria-hidden="true">↙</span></figcaption></figure>
</section>
<section class="intro-section"><div class="section-label"><span class="eyebrow">Right now</span><a class="current-work" href="https://www.hadrian.co/">Special Projects<br>@ Hadrian {arrow()}</a></div><div class="intro-copy"><p>I studied finance, spent two years in investment banking, then took a year off to learn machine learning. That led to research at UC San Diego. Now I'm at <a href="https://www.hadrian.co/">Hadrian</a>.</p><p>Along the way: reinforcement learning, language models, a backpack, and quite a few long-term pet sits.</p><a class="text-link" href="{PIVOT}">Why I made the switch {arrow()}</a></div></section>
<section class="home-work"><div class="section-heading"><h2>A few things I've worked on<span class="blue">.</span></h2><a class="text-link" href="professional.html">All work {arrow()}</a></div>
<div class="home-projects"><a class="project-preview featured-preview" href="research.html"><div class="preview-visual research-visual"><span class="eyebrow">ICML 2026 · Lead author</span><span class="research-question">What does a<br>language model<br><em>learn from chess?</em></span><div class="research-foot"><span>SFT → RL → Reasoning</span><span aria-hidden="true">↗</span></div></div><div class="preview-caption"><span>01 / Research</span><strong>How reasoning evolves</strong></div></a><a class="project-preview" href="professional.html#dungeon-coder"><div class="preview-visual dungeon-visual"><img src="/assets/thumbnails/dungeoncoder_overview.gif" width="600" height="400" loading="lazy" alt="Dungeon Coder: generated 3D assets in a dungeon editor"></div><div class="preview-caption"><span>02 / Building</span><strong>Dungeon Coder</strong></div></a></div></section>
<section class="elsewhere-teaser"><a class="travel-image" href="personal.html"><img src="/assets/pics/sabbatical/vikosgorge.jpg" width="1008" height="756" loading="lazy" alt="Lucas at Vikos Gorge in Greece at sunset"></a><div class="travel-teaser-copy"><span class="eyebrow">Away from the laptop</span><h2>There was a<br><em>scenic route.</em></h2><p>I could study at home in Wisconsin, or in Airbnbs and pet sits around the world. One of those sounded more fun.</p><a class="text-link" href="personal.html">The places & the stories {arrow()}</a></div></section>
'''

PROJECTS = [
    dict(id='rl-gym', title='RL Benchmarking Gym', tag='Reinforcement learning', img='breakout_rainbow.gif', alt='A reinforcement learning agent playing Atari Breakout', summary='An RL engine built from scratch to implement, compare, and ablate algorithms — from the baselines to state of the art.', tech='Python · Gymnasium · DQN · Rainbow', href='https://lucasdino.notion.site/RL-Benchmarking-300c748e5e4a80cb9a42e3d8be2f7c58?source=copy_link', code='https://github.com/lucasdino/rl-gym-benchmarking'),
    dict(id='dungeon-coder', title='Dungeon Coder', tag='Generative AI / Full stack', img='dungeoncoder_overview.gif', alt='Dungeon Coder interface showing an interactive 3D dungeon', summary='From a prompt to a 3D dungeon. Image generation and image-to-3D models create custom assets for interactive worlds or 3D printing; classical algorithms and LLM agents build the dungeon around them.', tech='React · Three.js · Self-hosted vision models', href='https://lucasdino.notion.site/Dungeon-Coder-20dc748e5e4a802cb281ce01fe6272b7?source=copy_link', code='https://github.com/lucasdino/ai-battlemaps'),
    dict(id='rover', title='A rover that finds its way', tag='Robotics / Autonomy', img='ekfslam_webster.gif', alt='Rover mapping its surroundings with EKF-SLAM', summary='An autonomy stack for an uncalibrated four-wheel rover: vision, EKF-SLAM implemented from scratch, and path planning.', tech='ROS2 · OpenCV · Python', href='https://lucasdino.notion.site/4-Wheel-Rover-Autonomous-Control-31ec748e5e4a8081a7c7ec3951d27317?source=copy_link'),
    dict(id='rl-driver', title='Teaching an AI to drive', tag='Reinforcement learning / Games', img='rldriver_originaltrack.gif', alt='An agent learning to navigate a custom racing track', summary='First I made a racing game. Then I trained a Double Q-learning agent to drive it.', tech='Pygame · Double Q-learning', href='https://lucasdino.notion.site/Teaching-AI-to-Drive-my-Custom-Racing-Game-214e45ce19704294bd365308a77c68b4?pvs=4', code='https://github.com/lucasdino/AI-Driving'),
    dict(id='anomaly-detection', title='Finding the unusual', tag='Applied machine learning', img='anomalydetection_thumbnail.jpg', alt='Time-series anomaly detection plots', summary='A real-time, interpretable anomaly detection system for noisy time-series data, built for a San Diego healthtech company.', tech='Kernel ridge regression · Time-series analysis', href='https://lucasdino.notion.site/Anomaly-Detection-12bc748e5e4a807e8c7afff86b16d975?pvs=4'),
    dict(id='word2vec', title='Recreating Word2Vec', tag='Natural language processing', img='recreating_word2vec.jpg', alt='Word embeddings and vector arithmetic from the Word2Vec project', summary='Building the whole pipeline: clean English Wikipedia, write a tokenizer, train an embedding model, and recreate vector arithmetic.', tech='Tokenization · Embeddings · Model training', href='https://lucasdino.notion.site/Recreating-Word2Vec-25c1e86e08f14087a49c027a85bd5198')
]
WRITING = [
    ('01', 'Changing direction', 'Why Pivot?', 'Leaving finance, taking a year to study ML, and starting grad school.', PIVOT),
    ('02', 'Work & data', 'Two years of banking, in hours.', 'I tracked my working hours as an investment banking analyst. Here are the charts.', 'https://lucasdino.notion.site/My-Honest-Working-Hours-as-an-Investment-Banking-Analyst-03845324522a4b7785f6b752cf8b0da2?pvs=4'),
    ('03', 'Machine learning', 'From attention to Llama 3.', 'The improvements that shaped the modern decoder-only transformer.', 'https://lucasdino.notion.site/What-is-a-SoTA-Transformer-Model-90d21f0a142349629a416ecce45cd671?pvs=4'),
    ('04', 'Technology & business', 'What makes Nvidia so hard to compete with?', 'A technically approachable look at its multi-trillion-dollar moat.', 'https://lucasdino.notion.site/Nvidia-s-Multi-Trillion-Dollar-Moat-Explained-187c748e5e4a803dbd35dfeea250913a?pvs=4')
]

def project_card(p, i):
    code = f'<a href="{p["code"]}" class="text-link">Code {arrow()}</a>' if p.get('code') else ''
    return f'''<article class="work-project work-project-{i}" id="{p['id']}">
    <a class="work-image" href="{p['href']}" aria-label="Read about {p['title']}"><img src="/assets/thumbnails/{p['img']}" alt="{p['alt']}" loading="lazy"></a>
    <div class="work-project-copy"><div class="project-kicker eyebrow"><span>0{i}</span><span>{p['tag']}</span></div><h2><a href="{p['href']}">{p['title']}</a></h2><p>{p['summary']}</p><p class="project-tech">{p['tech']}</p><div class="project-links"><a href="{p['href']}" class="text-link">Project notes {arrow()}</a>{code}</div></div></article>'''

def work_page():
    cards = ''.join(project_card(p, i) for i, p in enumerate(PROJECTS, 1))
    writing = ''.join(f'<a class="writing-row" href="{url}"><span class="writing-number">{n}</span><div><span class="eyebrow">{tag}</span><h3>{title}</h3><p>{desc}</p></div>{arrow()}</a>' for n, tag, title, desc, url in WRITING)
    return f'''<div class="page-kicker eyebrow"><span>01 / Projects & writing</span><a href="https://github.com/lucasdino">GitHub {arrow()}</a></div>
    <section class="page-title"><h1>WORK<span>.</span></h1><div><p class="title-aside">Things I've built.<br><em>Things I've learned.</em></p><p class="title-summary">Reinforcement learning, robotics, language models, and a dungeon or two.</p></div></section>
    <nav class="section-jumps" aria-label="On this page"><a href="#projects">Projects <span>06</span> ↓</a><a href="#writing">Writing <span>04</span> ↓</a><a href="research.html">Research ↗</a></nav>
    <section id="projects" class="work-grid" aria-label="Projects">{cards}</section>
    <section class="writing-section" id="writing"><div class="section-heading"><h2>Some things I've written<span class="blue">.</span></h2><span class="eyebrow">04 pieces</span></div><div class="writing-list">{writing}</div></section>'''

research = '''<div class="page-kicker eyebrow"><span>02 / Machine learning</span><span>UC San Diego</span></div>
<section class="page-title research-title"><h1>RESEARCH<span>.</span></h1></section>
<div class="research-intro"><p class="title-aside">How do language models<br><em>learn to reason?</em></p><div><p>My research at UC San Diego focused on reinforcement learning for language models with <a href="https://pearls-lab.github.io/">PEARLS Lab</a>. I also worked with <a href="https://cseweb.ucsd.edu/groups/progsys/">UCSD ProgSys</a>.</p></div></div>
<article class="paper-feature"><div class="paper-meta"><span class="eyebrow">01 / Featured paper</span><div><span>ICML 2026</span><span>NeurIPS 2025 FoRLM · Oral</span></div></div><h2>How Reasoning Evolves <br>from Post-Training Data: <br><em>An Empirical Study Using Chess</em></h2><p class="paper-authors"><strong>Lucas Dionisopoulos</strong> · Nicklas Majamaki · Prithviraj Ammanabrolu</p><div class="paper-links"><a class="solid-link" href="https://arxiv.org/abs/2604.05134">Read the paper ↗</a><a class="text-link" href="https://github.com/lucasdino/lang-chess">Code, models & data ↗</a><a class="text-link" href="/assets/files/llm_chess_neurips_forlm_2025.pdf">Workshop paper ↗</a></div>
<div class="paper-summary"><p>A strong chess move and a faithful explanation don't always come together. We studied how supervised fine-tuning data shapes a 7B model's reasoning after reinforcement learning.</p><div><h3>The finding</h3><p>Training on the best move produced strong performance, but reasoning could be inconsistent with that move. Training on multi-move trajectories gave comparable performance with more faithful reasoning and more stable RL.</p></div></div>
<figure class="paper-figure"><a href="/assets/thumbnails/llmchess_takeaway.jpg" target="_blank" rel="noopener" aria-label="Open the research overview figure at full size"><img src="/assets/thumbnails/llmchess_takeaway.jpg" width="1058" height="432" alt="Research overview: best-move and best-line supervised training, reinforcement learning curves, and comparison of reasoning faithfulness." loading="lazy"></a><figcaption>From supervised fine-tuning to RL: the training data changes what follows. <a href="/assets/thumbnails/llmchess_takeaway.jpg" target="_blank" rel="noopener">View full size ↗</a></figcaption></figure></article>
<section class="other-research"><div class="section-heading"><h2>Other investigations<span class="blue">.</span></h2></div><div class="research-grid"><article><a class="research-image" href="https://lucasdino.notion.site/Attempted-Neural-A-Guided-Search-on-ARC-AGI-171c748e5e4a801796f6d7e13f78714c?pvs=4"><img src="/assets/thumbnails/arcprize_pcfg_thumbnail.jpg" alt="A grid transformation task from ARC-AGI" loading="lazy"></a><span class="eyebrow">02 / Neurosymbolic learning</span><h3>A* neural guided search<br>on ARC-AGI</h3><p>A synthetic data pipeline and an image embedding model, trained from scratch, paired with a probabilistic context-free grammar to explore program search.</p><div class="project-links"><a class="text-link" href="https://lucasdino.notion.site/Attempted-Neural-A-Guided-Search-on-ARC-AGI-171c748e5e4a801796f6d7e13f78714c?pvs=4">Research notes ↗</a><a class="text-link" href="/assets/files/291C_ARCreport_vF.pdf">Report ↗</a></div></article><article><a class="research-image" href="https://lucasdino.notion.site/Philosophize-That-147c748e5e4a8054b857eee9e47bf62d?pvs=4"><img src="/assets/thumbnails/philosophize_thumbnail.jpg" alt="Philosophical text analysis project overview" loading="lazy"></a><span class="eyebrow">03 / Language & philosophy</span><h3>Philosophize That</h3><p>Building a corpus of philosophical texts, separating signal from correlated noise, and using document embeddings to classify the philosophical basis of my own journal entries.</p><div class="project-links"><a class="text-link" href="https://lucasdino.notion.site/Philosophize-That-147c748e5e4a8054b857eee9e47bf62d?pvs=4">Research notes ↗</a><a class="text-link" href="/assets/files/philosophize_that.pdf">Report ↗</a></div></article></div></section>'''

personal = f'''<div class="page-kicker eyebrow"><span>03 / Life outside work</span><span>A few places along the way</span></div>
<section class="page-title elsewhere-title"><h1>ELSEWHERE<span>.</span></h1></section>
<section class="travel-intro"><div><h2>153 days.<br><em>One backpack.</em></h2><p>After banking, I wanted time to study machine learning. I also wanted to see a bit of the world. Long-term Airbnbs and pet sits made room for both.</p><a class="text-link" href="{STUDY}">What I studied on my year off {arrow()}</a></div><figure><img src="/assets/pics/sabbatical/meteora.jpg" width="1008" height="756" alt="The rock formations and monasteries of Meteora in Greece" fetchpriority="high"><figcaption>Meteora, Greece · From the sabbatical</figcaption></figure></section>
<section class="travel-journal" aria-labelledby="journal-title"><div class="section-heading"><h2 id="journal-title">The travel journal<span class="blue">.</span></h2><span class="eyebrow">Sabbatical / 2023</span></div><p class="journal-instructions">Choose a place on the map, or follow the trip one stop at a time.</p>
<div class="journal-toolbar"><div><label for="region-select">Chapter</label><select id="region-select"><option value="all">The whole trip</option></select></div><button type="button" id="map-reset" class="subtle-button">Reset map ↺</button></div>
<div class="journal-grid"><div class="map-column"><div id="travel-map" role="region" aria-label="Interactive map of Lucas's sabbatical"><p class="map-fallback">The map is loading. You can also browse the journal using the controls.</p></div><div class="map-caption"><span>Photos & notes by Lucas</span><span>22 flights. A lot of ground covered.</span></div></div><div class="journal-reader"><div class="stop-navigation"><button type="button" id="previous-stop" aria-label="Previous travel stop">←</button><span id="stop-count" class="eyebrow" aria-live="polite">The whole trip</span><button type="button" id="next-stop" aria-label="Next travel stop">→</button></div><div id="stop-story"><figure><button type="button" class="story-photo" aria-label="Enlarge travel photograph"><img id="stop-photo" src="/assets/pics/sabbatical/backpack.jpg" alt="The backpack Lucas carried on his trip"></button></figure><div class="story-copy"><span class="eyebrow" id="stop-region">Leaving home</span><h3 id="stop-name" aria-live="polite" aria-atomic="true">No return date.</h3><div id="stop-blurb"><p>I left with a backpack and no return date. Five months, 22 flights, and a lot of studying later, I was home again.</p><p>These are my photos and notes from along the way.</p></div><a id="stop-map-link" class="text-link" href="https://www.openstreetmap.org/" target="_blank" rel="noopener">Open map ↗</a></div></div></div></div>
<div id="stop-list" class="stop-list" aria-label="Travel stops"></div>
<noscript><p>The interactive journal needs JavaScript. A few highlights from the trip are below.</p></noscript></section>
<section class="travel-highlights"><div class="section-heading"><h2>A few favorites<span class="blue">.</span></h2></div><div class="travel-photo-grid"><figure><img src="/assets/pics/sabbatical/papou.jpg" alt="Lucas's Papou during a family visit in Kalamata" loading="lazy"><figcaption><span class="eyebrow">Kalamata, Greece</span><h3>A month in the old country.</h3><p>Linear algebra, machine learning, walks to the pier, and a visit from my Papou and parents.</p></figcaption></figure><figure><img src="/assets/pics/sabbatical/dotty.jpg" alt="Dot, the dog Lucas looked after in Tasmania" loading="lazy"><figcaption><span class="eyebrow">Tasmania, Australia</span><h3>Excellent study company.</h3><p>37 days in Hobart, hiking nearby and looking after Dot. I still miss this dog.</p></figcaption></figure><figure><img src="/assets/pics/sabbatical/canaldamour.jpg" alt="Lucas's sketch of Canal d'Amour in Corfu" loading="lazy"><figcaption><span class="eyebrow">Corfu, Greece</span><h3>A good place to stop.</h3><p>A shady outcropping, a sketchbook, and one of my favorite afternoons of the trip.</p></figcaption></figure></div></section>
<section class="more-personal"><div class="section-heading"><h2>Closer to home<span class="blue">.</span></h2></div><div class="personal-links"><a href="https://leelounsbury.com/john-muir-trail-2025-09/"><img src="/assets/thumbnails/jmt_2025.jpg" alt="Mountain scenery from the 2025 John Muir Trail trip" loading="lazy"><div><span class="eyebrow">On the trail / 2025</span><h3>John Muir Trail {arrow()}</h3><p>A trip cut short by wildfires. Still came back with some great photos.</p></div></a><a href="https://www.notion.so/lucasdino/Clean-Our-Green-271c748e5e4a800d8b54de1c0886d2b5"><img src="/assets/thumbnails/clean_our_green.jpg" alt="Volunteers cleaning a St. Louis park" loading="lazy"><div><span class="eyebrow">St. Louis / College</span><h3>Clean Our Green {arrow()}</h3><p>A project I started in college to clean up parks around St. Louis.</p></div></a></div></section>
<dialog id="photo-dialog" aria-label="Travel photograph"><button class="close-photo" type="button" aria-label="Close photograph">Close ×</button><img id="large-photo" alt=""><p id="large-photo-caption"></p></dialog>'''

contact = '''<div class="page-kicker eyebrow"><span>04 / Get in touch</span><span>Los Angeles, California</span></div>
<section class="contact-page"><div class="contact-title"><h1>SAY<br><em>hello.</em><span aria-hidden="true">↗</span></h1></div><div class="contact-content"><span class="eyebrow">Always up for a conversation</span><h2>In LA?<br>Let's grab a coffee.</h2><p>Or send me a note from wherever you are. I'd be happy to chat.</p><div class="email-block"><span class="eyebrow">Email</span><a class="email-address" href="mailto:lucasdionisopoulos@gmail.com">lucasdionisopoulos<wbr>@gmail.com <span aria-hidden="true">↗</span></a><span class="email-hint">First name + last name, at Gmail.</span></div><div class="contact-social-list"><a href="https://www.linkedin.com/in/lucasdionisopoulos/"><span>LinkedIn</span><span>Professional ↗</span></a><a href="https://github.com/lucasdino"><span>GitHub</span><span>Code ↗</span></a><a href="https://x.com/dinoacropolis"><span>X / Twitter</span><span>@dinoacropolis ↗</span></a></div></div></section>'''

if __name__ == '__main__':
    page('index', 'About', home)
    page('professional', 'Work', work_page())
    page('research', 'Research', research)
    page('personal', 'Elsewhere', personal,
         '<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""><script defer src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>',
         '<script type="module" src="js/journal.js"></script>')
    page('contact', 'Contact', contact)
    print('Built 5 static pages.')
